# Generated by Django 2.0 on 2017-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notecontent',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='notecontent',
            name='isOpen',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
