# Generated by Django 2.0 on 2017-12-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171229_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload/other')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
