# Generated by Django 2.0 on 2017-12-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171231_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='note_type',
            field=models.CharField(max_length=30),
        ),
    ]
